repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version to use for pre-commit hooks
    rev: v0.1.11
    hooks:
      # Run the Ruff formatter
      - id: ruff-format
      # Run Ruff linter with automatic fixes
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Ensure files end with a newline
      - id: end-of-file-fixer
      # Remove trailing whitespace
      - id: trailing-whitespace
      # Check for merge conflicts
      - id: check-merge-conflict
      # Check YAML files
      - id: check-yaml
      # Check for large files
      - id: check-added-large-files
        args: ['--maxkb=5000']