from huggingface_hub import InferenceClient
from dotenv import load_dotenv
import os


load_dotenv()
client = InferenceClient(api_key=os.getenv("HUGGINGFACE_TOKEN"))


content="""
R�ponds � la question suivante : Que penser de la Russie ? . Pour y r�pondre, tu utiliseras les informations contenues dans les documents suivants: 
            

 Document 0: Donc on voit bien que la Chine et la Russie forment un couple, un duo avec, comme je le disais, une r�partition des t�ches bien d�finies. Il y a peut-�tre un d�saccord, je vais le d�voquer plus tard, je vais faire de la parole � Laurent, je vais au Mondey apr�s. 

  Document 1: Et on reproche � la Russie de ne pas se comporter comme la Chine, ce n'est pas possible non plus. Et donc voil�, il y a des r�alit�s concr�tes. La Chine est une culture ethnocentr�e, qui ne r�ve pas de devenir le nouveau h�g�mon, qui cherche tout simplement � avoir un monde multipolaire on le respecte � la souverainet� de chacun. La Russie adh�re � ce logiciel-l�, mais elle a �galement un logiciel universaliste, gr�ce � la chr�tient� orthodoxe, etc., qui fait qu'elle veut convaincre les autres, contrairement � la Chine, qui dit aux autres, si vous voulez �tre convaincu, venez voir par vous-m�me. Et donc, on a cette richesse culturelle et civilisationnelle qui alimente la richesse de la g�opolitique contemporaine. 

  Document 2: Ce qui fait que �a ne laissera pas d'autres solutions aux Chinois que de suivre d'une certaine fa�on la Russie dans la confrontation. Parce qu'en fait, c'est les Am�ricains qui ne laissent pas le choix aux Chinois qui allument des feux dans le Myanmar, qui multiplient les provocations � Ta�wan, qui renforcent leur pr�sence en Asie pacifique, qui foutent la pagaille avec Isra�l dans le Proche-Orient. Tu disais effectivement que les Russes ont contraint les Chinois � les suivre, notamment en Ukraine. Je pense que les Chinois sont contraints que les Russes n'avaient pas le choix, parce qu'ils constatent qu'eux-m�mes sont contenus par les Am�ricains, et qu'il ne leur laisse pas le choix. Mais de toute fa�on, il est clair, compte tenu des temp�raments diff�rents et des cultures diff�rentes. Les Chinois ont compris qu'ils �taient le dernier domino � abattre pour les g�mons anglo-am�ricains. Et l�, tu disais, pour l'instant, c'est que des soldats russes qui meurent. 

  Document 3: Donc elle a int�r�t plut�t � stabiliser la chose, � instaurer la paix. Et donc la guerre en Ukraine, elle soutient la Russie indirectement. L� encore, malgr� elle, c'est �galement subi du c�t� chinois, mais la Chine aurait aim� qu'il n'y aurait pas de guerre en Ukraine, que la Russie ne soit pas intervenue militairement. Et donc � un certain moment, �a deviendra tout simplement intenable. C'est-�-dire que plus la Russie se d�fendra comme elle doit le faire, plus la Chine aura des difficult�s � suivre la Russie dans sa dynamique de d�fense de sa propre souverainet�. Donc � terme, je ne sais pas comment �a va se d�velopper. Est-ce que la Chine va d�finitivement sortir de sa timidit� ou de son approche indirecte strat�gique de long terme pour rejoindre la Russie dans un front commun direct et frontal ? ou bien il y aura une rupture � terme entre les deux, parce que les agendas sont intenables. 

  Document 4: Il y a la question du Pakistan, �a m�riterait un deuxi�me entretien. Il y a la question du Kazakhstan, qui selon moi est probablement le futur foyer de d�stabilisation que Washington va activer pour opposer la Chine � la Russie, sachant qu'on a un sch�ma relativement similaire � celui d'Ukraine, c'est-�-dire un syst�me politique qui est n� de la dislocation de l'Union sovi�tique et qui a connu une russophobie qui ne cesse de monter crescendo et qui a une minorit� russe qui repr�sente quand m�me un tiers de la population, qui est de plus en plus �cart�e. Et �a pourrait �galement �tre un moyen d'opposer la Chine � la Russie, sachant que la Chine a des int�r�ts au Kazakhstan et pareil pour la Russie. Donc peut-�tre un deuxi�me entretien pour d�velopper � chaque fois un nouvel aspect de cette question �minemment complexe. Les amis... Et on pourra parler de la Mongolie aussi, qui est un peu l'angle mort de la g�opolitique en Asie, mais qui pourrait �tre aussi un foyer de d�stabilisation entre la Chine et la Russie, parce que vous savez quand m�me que le pr�sident de la Mongolie appelle les �tats-Unis le troisi�me voisin de la Mongolie. Ah d'accord. 

  Document 5: �a, c'est vraiment important, je pense. �a permet de revenir � la question du monde arabe, arabo-musulman et de la Chine. C'est vrai qu'il y a eu une manipulation, qu'il y a un soft power am�ricain et isra�lien qui a r�ussi � convaincre les populations arabes et les foules arabes que la Chine est un ennemi de l'islam. pareil pour la Russie, qui est pr�sent�e comme un ennemi de l'islam, qui tue les Syriens, qui a tu� les Tch�tch�nes, etc. Et malheureusement, �a a march�. Et en plus, �a a march� parce que �a a �t� fond� sur un st�r�otype, peut-�tre pas un st�r�otype, mais sur une opinion des foules arabes, selon laquelle la Chine, �tant communiste, elle est donc ath�e, et �tant ath�e, elle est antireligieuse. Donc aujourd'hui, pour l'arabe lambda, m�me si on sait tr�s bien que dans le monde arabe, l'opinion publique des foules ne p�se pas beaucoup dans la balance, mais quand m�me, Pour un arabe lambda, la Chine, c'est un pays ath�e qui mange des chiens et qui tue des musulmans. De l'autre c�t�, la Chine n'arrive toujours pas � d�ployer une contre-propagande. 

  Document 6: Alors, il faut aller sur le site de CGTN pour la voir. Effectivement, c'est tr�s peu connu. Il n'y a personne qui sait que c'est l'existence fran�aise. Donc, il faut vraiment un investissement. Parce que CGTN, j'en connais l'existence, mais tr�s peu de gens connaissent. Et il faudrait vraiment un investissement pour au moins, je l'ai dit, avoir une fen�tre. c'est-�-dire une fen�tre qui permet aux Chinois de voir l'Occident, je pense qu'ils le voient suffisamment, mais surtout aux Occidentaux d'avoir une fen�tre sur la Chine. Non mais tu as raison, parce que la cha�ne en question, la subtilit� de Racha Today, c'est qu'elle a r�ussi, tout en ayant des financements de l'�tat russe, � fonder une cha�ne qui est les apparences d'une cha�ne priv�e. d'une cha�ne cool, d�contract�e, qui invite des Fran�ais avec des opinions diff�rentes, qui invite m�me des gens oppos�s � la Russie, venir d�battre, on l'a vu, avec Taddy, etc. Par contre, quand on voit la cha�ne chinoise, on dirait une cha�ne publique, c'est-�-dire les gens sont coinc�s, ils ne bougent pas. Il n'y a pas ce c�t� d�contract� qui touche les gens, ce c�t� cool, ce c�t� moderne, post-moderne, avec les g�n�riques, etc. Donc peut-�tre que la Chine doit �galement int�grer ces codes qui parlent aux Occidentaux, pour mieux les toucher. d'autant plus que de par mon emploi pr�c�dent je connais un petit peu parce que je travaille dans la diplomatie culturelle et audiovisualisation fran�aise � une certaine �poque et justement l'installation du bureau de CGTN en Europe �tait un des dossiers sur lesquels on avait travaill� et il est int�ressant de voir que la France qui se d�clare toujours �tre une grande amie id�ologique de la Chine en fait on avait une position qui �tait beaucoup moins int�ressante que les Allemands et les Anglais. Je crois que le bureau Europe a fini par ouvrir en Angleterre, alors que ce n'est vraiment pas l'endroit o� il faut, pour la Chine, se positionner. Ce n'est pas l� qu'elle trouvera le plus d'amis en Europe. Et c'est pareil sur les questions d'habillage de la cha�ne, et juste comme �a, c'�tait quelque chose que la France se targuait de faire dans tous les pays en d�veloppement, de proposer justement � ce que des cha�nes un petit peu aust�res, des cha�nes publiques un peu aust�res, puisse �tre un petit peu plus sexy. Mais la Chine n'a jamais pris cette offre s�rieusement parce que �a n'�tait pas que de l'habillage de cha�ne qui �tait propos�, mais il y avait aussi des recommandations �ditoriales, quel type de sujet � traiter. Et on voyait que syst�matiquement, c'�tait des sujets soci�taux. On conseillait, �a serait bien de mettre du soci�tal pour attirer le chalon. 

  Document 7: Donc il dit, on va arr�ter les frais, on n'a plus les moyens de dominer le monde, on va n�gocier avec la Russie et avec la Chine. La Russie, on va la laisser continuer � tisser des liens avec l'Europe, avec l'Europe de l'Ouest, et on va privil�gier une relation avec la Chine, une relation notamment �conomique, commerciale, et on va laisser la Chine d�velopper ses relations, notamment avec les pays musulmans d'Asie centrale, etc. Et il dit, et nous devons d�coupler donc les Russes et les Chinois, et activer des tensions, notamment sur les questions territoriales. et c'�tait en fait l� la strat�gie la vision la plus intelligente pour pour les int�r�ts des �tats unis on est d'accord m�me kissinger a �t� tr�s sage voil� pas pour conflit mais la r�alit� c'est ceux qui prennent la d�cision voil� donc c'est ce qui a �t� fait ce qui a �t� fait Il y a eu la phase Trump qui rentrait en confrontation avec la Chine, mais pour des raisons �conomiques, logique protectionnique, etc. et qui a voulu, lui, pr�sident des �tats-Unis, apaiser les tensions avec la Russie. Mais m�me durant son mandat, il y a eu plus de sanctions contre la Russie que durant le mandat d'Obama. Et en r�alit�, on voit que l'�tat profond am�ricain, qui est dans une sorte d'hubris, m�me autodestructrice, veut une confrontation � la fois contre la Russie et contre la Chine. C'est-�-dire qu'ils ont continu� � mettre des sanctions contre la Russie. Ils ont, � partir de 2021, je l'ai d�j� dit plusieurs fois, notamment chez toi, Rachid, ils ont retir� des troupes, d�j� d'Afghanistan, puis d'Arabie Saoudite, d'Irak, de Syrie, pour renforcer leur pr�sence en Asie pacifique et pour pr�parer la guerre en Ukraine. Donc il y a v�ritablement une volont� d'affronter les deux, de fa�on diff�rente, mais d'affronter les deux. 

  Document 8: Yusuf ? Par rapport aux questions du self-power et de l'absence de la Chine, notamment au niveau m�diatique, un peu � l'image de la Russie qui avait d�velopp� Racha Today, Spoutnik, en arabe, en anglais, en espagnol, enfin, les principales langues. Et on voit que �a peut �tre �teint avec un bouton. Oui, �a c'est vrai, mais quand m�me, il y a eu une p�riode de plusieurs ann�es o� ces cha�nes ont quand m�me touch� beaucoup de gens. Et qu'aujourd'hui, il y a des gens, m�me s'ils sont d�branch�s m�diatiquement ces cha�nes-l�, il y a des gens qui vont les chercher sur internet. Alors oui, c'est pas aussi efficace que la machine de guerre am�ricaine, mais quand m�me �a a permis de toucher beaucoup de gens. Youssef, tu en penses quoi ? 

  Document 9: On le voit dans les go�ts du public chinois, par exemple. Pendant des d�cennies, il y avait une vingtaine de films �trangers qui pouvaient rentrer en Chine. Et c'�tait syst�matiquement les films am�ricains qui ramassaient le jackpot, on va dire, en termes d'audience. Et l�, �a fait cinq ou six ans que dans le top 10 des films les plus vus en Chine, il y a un film am�ricain, tout le reste c'est des films chinois m�me le public chinois ne regarde plus Hollywood avec la m�me fascination qu'il y a 10 ou 15 ans et donc � partir de l�, la Chine se dit mais qu'est-ce que je vais aller faire des films pour les occidentaux maintenant, j'ai pas besoin mon public se satisfait de films chinois si les pays occidentaux ne veulent pas de mes films, qui font des box office ph�nom�naux en termes de recettes c'est du jamais vu en Occident si l'Occident n'en veut pas moi j'y peux rien et l� encore c'est comme on disait aussi bien de la vue g�opolitique que culturel �a d�pend en fait de l'Occident, c'est l'Occident qui en fait ne fait pas venir des films chinois on les faisait venir � une �poque o� la Chine �tait pauvre o� il y avait Jean-Yimo qui nous montrait la Chine arri�r�e avec des concubines alors l� oui, l� on faisait venir parce que �a alimentait notre imaginaire paternaliste colonialiste de la Chine arri�r�e ils sont tous polygames Alors que maintenant que c'est des films o� la Russie r�ussit, on revient finalement toujours au point de part, c'est-�-dire le temp�rament des peuples, qu'on ne peut pas changer et qu'on ne doit pas juger. C'est-�-dire qu'on exige de la Chine de se comporter comme la Russie, et ce n'est pas possible. 

  Document 10: Il y a tr�s peu d'instituts culturels chinois dans le monde arabe. Il y en a un en Maroc et encore, quoi que. Il n'y a pas de communication, il n'y a pas de cha�ne chinoise en arabe, un peu comme Rasha Today en arabe, etc. Donc, � un certain moment, la Chine devra investir le champ de la guerre informationnelle et de la guerre cognitive. Laurent ? La propagande atlantiste, anti-chinoise �tait une machine, et d'ailleurs Vladimir Poutine l'a dit, c'est impossible � battre. Tous les m�dias internationaux sont anglo-am�ricains, et ni la Russie, ni la Chine, ni l'Iran ne peuvent recr�er �a de fa�on � pouvoir concurrencer. Donc je pense que de toute fa�on, la Chine et probablement la Russie ont r�alis� que le soft power, de toute fa�on, c'�tait bas� sur des m�dias, sur du cin�ma, et que par d�finition, tout ce qui est cin�ma, c'est faux. et on finit par s'en rendre compte un jour ou l'autre. Le cin�ma hollywoodien, je pense qu'il est en p�riode de d�clin, il ne fait plus son travail de propagande vis-�-vis du monde et c'est pour �a que je pense qu'il y a un autre style de propagande qui est en train de se d�velopper depuis les Etats-Unis, qui n'a rien � voir avec le cin�ma, mais �a c'est un sujet compl�tement diff�rent. Mais la Chine n'a pas envie de r�pliquer �a, je pense que la Chine �tait vraiment... C'est d'ailleurs ce qu'a fait Xi Jinping r�cemment, il a diff�rentes �tapes des d�j� un an maintenant, il y a eu une annulation des visas, la n�cessit� de demander un visa pour visiter la Chine. Et en fait, il a dit� Pour qui ? 

  Document 11: Qu'est-ce qui fait que c'est impossible ? Parce qu'en Union sovi�tique, les bolcheviques ont au contraire combattu la civilisation russe, notamment en mettant en avant les minorit�s, etc., pour diluer l'identit� russe � travers le communisme. Alors en Chine, c'est le contraire, enfin pas le contraire, mais disons que le communisme a �t� un mode d'expression de l'identit� chinoise. Oui, tout � fait. 

  Document 12: Et que la Chine, il n'y a pas de Chinois qui meurent. Et autre chose, c'est qu'il y a un d�but de divergence dans l'agenda russe et l'agenda chinois, sur le moyen et long terme, parce qu'avant le conflit en Ukraine, l'agenda des deux �tait align�. C'est-�-dire, c'�tait de r�agencer, de r�former en profondeur l'ordre mondial de telle mani�re � le rendre multipolaire. Et donc �a passait �galement par les institutions internationales, soit en cr�ant des institutions alternatives ou FMI � la Banque mondiale � travers les BRICS, soit en proposant de r�former l'ONU, de r�former l'existant. Or avec la guerre en Ukraine, la Russie a connu malgr� l'un changement brutal dans son agenda o� d�sormais il n'est plus question de r�former quoi que ce soit. Parce que la Russie a �t� �ject�e de toutes ces structures qu'elle voulait r�former avec la Chine. et donc la Russie est de fait dans une logique aujourd'hui de table rave o� il s'agit de fonder un ordre nouveau sur les ruines de l'ordre actuel Et donc on l'a amen� � une forme de jusque-boutisme dans lequel la Chine ne s'inscrit pas. La Chine est toujours dans la m�me volont� de r�forme. 

  Document 13: Et en fait, c'est les �changes de personnes. Ils ont dit qu'au lieu de regarder la t�l�vision, de lire les journaux et de les �couter, d'iffamer la Chine, venez vous rendre compte par vous-m�me, mais ce que c'est. Il n'y a plus besoin de visa, ni pour le tourisme, ni pour les affaires. Donc, il y a un nombre tr�s important de gens qui sont venus du monde entier. Et on voit beaucoup sur TikTok, sur YouTube, des �trangers, des familles enti�res qui vont en chine et qui se prennent en qui se prennent en vid�o dans des tarifs ont telle ville et on est �tonn� et c'est d�velopp� les gens sont sympas on mange bien il ya des gens qui vont aux indiens qui font des reportages en disant il se passe pas ce qu'on vous a racont� et en fait c'est �a le sort enfin la tentative de soft power �a va �tre �coutez on va pas faire de soft power parce que par d�finition de soft power c'est une autre propagande donc on va pas venir vous rendre compte par vous m�me et �a je pense que c'est en vigueur ce qui est en en train de se passer en Russie, o� on voit qu'il y a en fait une simplification du processus de demande de visa pour la Russie. Et en fait, l'id�e, c'est au plus on va nous diaboliser � l'�tranger, au plus il y a des gens qui vont finir par se poser la question, mais en fait, est-ce que �a serait pas plus simple d'y aller moi-m�me ? 

  Document 14: Et donc, ils ont envoy� des navires de guerre au large de la Syrie, pour frapper. Les Russes ont positionn� des navires de guerre, et les Chinois ont envoy� deux navires de guerre, mais pour observer. Et donc, la Chine commence petit � petit � marquer sa pr�sence, Et l�, �a a �t� beaucoup plus spectaculaire ces derni�res ann�es avec la r�conciliation entre l'Arabie saoudite et l'Iran. Mais en fait, cette r�conciliation est le r�sultat d'une n�gociation qui a commenc� autour de 2021 avec des �missaires saoudiens et iraniens qui se sont rencontr�s en Irak. Mais effectivement, la Chine a jou� un r�le important parce que la Chine est une grande puissance commerciale qui d�veloppe depuis 2012 le One Belt, One Road, les nouvelles routes de la soie. 

  Document 15: On se rappelle des morts en Cor�e dans les ann�es 50. on se rappelle c'�tait des on va dire un nombre de victimes bien sup�rieur � ce qui se passe actuellement en Ukraine alors bon c'est toujours � d�plorer mais les chinois c'est pas le nombre de pertes humaines qui leur fait peur �a on le voit dans tout oui non mais m�me ils ne r�fl�chissent pas comme �a ils ne se disent pas on est 1.4 milliards on pourrait en perdre 800 millions et �a serait encore bien mais ce que je veux dire c'est qu'ils n'ont pas peur d'aller au conflit pour l'instant ce n'est pas leur tour mais ils savent tr�s bien que leur tour va venir mais ce que je veux dire c'est que les Chinois savent qu'ils sont le dernier domino � battre et donc effectivement ils n'ont pas le choix que d'aider, d'assister la Russie pour l'instant dans sa r�sistance alors ce ne sera pas une assistance militaire avec des troupes au sol mais c'est une assistance logistique Alors, pas d'armes offensives, des chambres... choses comme �a. 

 . Ne cite pas les documents et r�pond en fran�ais, n'inclue pas de faits non mentionn�s explicitement dans les documents dans ta r�ponse"""

messages = [
	{
		"role": "user",
		"content": content
	}
]

completion = client.chat.completions.create(
    model="Qwen/QwQ-32B-Preview", 
	messages=messages, 
	max_tokens=500
)

print(completion.choices[0].message)