auto_merging: false
auto_merging_threshold: 7
auto_hybrid_search: false
chunk_overlap: 0
chunk_size: 1000
clone_database: false
clone_embedding_model: all-mpnet-base-v2
clone_persist: ./data/vector_stores/chroma_semantic_mapnet_v2
cot_enabled: true
embedding_model: BAAI/bge-m3
evaluate_generation: false
few_shot_hyde: false
filter_on_length: true
hybrid_search: true
length_threshold: 1
model_name: llama3
nb_chunks: 5
nb_rerank: 19
num_exemples: 50
num_queries: 1
path: data
persist_directory: ./data/vector_stores/chroma_semantic_bge_v2
reranker_model: BAAI/bge-reranker-v2-m3
search_type: similarity
splitting_method: semantic
token_compression: false
top_k: 5
use_hyde: false
use_multi_query: true
use_reranker: true
word_filter: alice
